- name: Build public directory
  run: |
    mkdir -p public
    python3 main.py
    # Copy your real map file to index.html
    if [ -f map.html ]; then
      cp map.html public/index.html
    elif [ -f Miller-map.html ]; then
      cp Miller-map.html public/index.html
    elif [ -f index.html ]; then
      cp index.html public/index.html
    else
      echo "<html><body><h1>Error: No map file found</h1></body></html>" > public/index.html
    fi

