name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run Miller-maps process
        run: python3 main.py
      - name: Build public directory
        run: |
          mkdir -p public
          echo "<html><body><h1>Miller-maps- Live!</h1><p>Last updated: $(date)</p></body></html>" > public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

