name: Build and Deploy Miller Maps

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Build Miller Maps application
        run: |
          python3 main.py
          echo "Build completed successfully"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Prepare deployment files
        run: |
          mkdir -p _site
          if [ -d "public" ]; then
            cp -r public/* _site/
          elif [ -d "docs" ]; then
            cp -r docs/* _site/
          else
            cp index.html _site/
          fi
          if [ ! -f "_site/index.html" ]; then
            echo "<h1>Miller Maps</h1><p>Custom Map Builder - Deployed Successfully</p><p>Build timestamp: $(date)</p>" > _site/index.html
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4